site_name: Timesheet History
site_url: https://app.forutan.com/timesheet-history

nav:
  - Main: "index.md"
  - Online help: "help.md"
  - Release notes: "release-notes.md"
  - Privacy policy: "privacy-policy.md"
