site_name: Forutan Software
site_url: https://app.forutan.com/
nav:
  - Home: index.md
  - Timesheet History: '!include ./timesheet-history/mkdocs.yml'
theme:
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  name: material
  favicon: images/favicon.png  
plugins:
  - search
  - monorepo
  - redirects:
      redirect_maps:
        'timesheet-history-privacy.md': 'https://app.forutan.com/timesheet-history/privacy-policy/'
extra:
  analytics:
    provider: google
    property: G-Q3X4P8HC7K        
